"""Add billing webhook events

Revision ID: d30c8c13cccc
Revises: 802b7f9e22f0
Create Date: 2026-09-19 16:11:33.214276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd30c8c13cccc'
down_revision: Union[str, Sequence[str], None] = '802b7f9e22f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parties', sa.Column('member_count', sa.Integer(), nullable=False))
    op.alter_column('quest_templates', 'class_affinity', postgresql_using='array_to_json(class_affinity)',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               type_=sa.JSON(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quest_templates', 'class_affinity', postgresql_using='array_to_json(class_affinity)',
               existing_type=sa.JSON(),
               type_=postgresql.ARRAY(sa.VARCHAR()),
               existing_nullable=True)
    op.drop_column('parties', 'member_count')
    # ### end Alembic commands ###
