"""Add DeletedAccount

Revision ID: d74782c1690e
Revises: d30c8c13cccc
Create Date: 2026-09-19 16:25:56.317784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd74782c1690e'
down_revision: Union[str, Sequence[str], None] = 'd30c8c13cccc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_sessions', sa.Column('refresh_token', sa.String(), nullable=True))
    op.add_column('auth_sessions', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('auth_sessions', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('auth_sessions', 'id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=False)
    op.add_column('deleted_accounts', sa.Column('reason', sa.String(), nullable=True))
    op.create_unique_constraint('uq_entitlements_user_id', 'entitlements', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'entitlements', type_='unique')
    op.drop_column('deleted_accounts', 'reason')
    op.alter_column('auth_sessions', 'id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.drop_column('auth_sessions', 'updated_at')
    op.drop_column('auth_sessions', 'expires_at')
    op.drop_column('auth_sessions', 'refresh_token')
    # ### end Alembic commands ###
