FALLBACK_CLASSES = {
    "VIT/INT": {"name": "Trail Scholar", "tagline": "Mind in the books, boots on the ground.", "blurb": "You learn best by doing and moving."},
    "VIT/CHA": {"name": "Golden-Hour Scout", "tagline": "Chasing the sunset with friends.", "blurb": "Your energy brings people together outdoors."},
    "VIT/GRIT": {"name": "Momentum Engine", "tagline": "Unstoppable force, immovable object.", "blurb": "Once you start, nothing breaks your stride."},
    "VIT/LCK": {"name": "Side-Quest Magnet", "tagline": "Always finding the hidden path.", "blurb": "You go for a walk and return with a story."},
    "INT/VIT": {"name": "Field Theorist", "tagline": "Testing hypotheses in the wild.", "blurb": "You apply your deep knowledge to the physical world."},
    "INT/CHA": {"name": "Streetlight Philosopher", "tagline": "Deep talks at 2 AM.", "blurb": "You draw people into meaningful, late-night conversations."},
    "INT/GRIT": {"name": "Quiet Tactician", "tagline": "Planning ten steps ahead.", "blurb": "You win through preparation and unwavering focus."},
    "INT/LCK": {"name": "Pattern Gambler", "tagline": "Finding the signal in the noise.", "blurb": "You see connections others miss and bet on them."},
    "CHA/VIT": {"name": "Parade Starter", "tagline": "Leading the charge with a smile.", "blurb": "Your enthusiasm gets everyone off the couch."},
    "CHA/INT": {"name": "Group-Chat Anchor", "tagline": "The keeper of the collective lore.", "blurb": "You are the central hub of your social circle's knowledge."},
    "CHA/GRIT": {"name": "Soft-Spoken Hype", "tagline": "Quietly lifting everyone up.", "blurb": "Your steady support is the foundation of your group."},
    "CHA/LCK": {"name": "Plot Catalyst", "tagline": "Making the unbelievable happen.", "blurb": "Where you go, interesting situations naturally follow."},
    "GRIT/VIT": {"name": "Long-Haul Ranger", "tagline": "Endurance is your weapon.", "blurb": "You outlast the competition through sheer stamina."},
    "GRIT/INT": {"name": "Blueprint Keeper", "tagline": "Executing the perfect plan.", "blurb": "You turn grand ideas into concrete, finished projects."},
    "GRIT/CHA": {"name": "Steady Flame", "tagline": "The reliable warmth in the cold.", "blurb": "People count on you when things get difficult."},
    "GRIT/LCK": {"name": "Deadline Bender", "tagline": "Pulling it off at the last second.", "blurb": "You somehow always manage to finish just in time."},
    "LCK/VIT": {"name": "Chaos Cartographer", "tagline": "Mapping the unpredictable.", "blurb": "You thrive in fast-paced, unpredictable environments."},
    "LCK/INT": {"name": "Lore Archivist", "tagline": "Collector of strange facts.", "blurb": "You stumble upon knowledge others spend years seeking."},
    "LCK/CHA": {"name": "Last-Minute Miracle", "tagline": "Saving the day, effortlessly.", "blurb": "You have a knack for showing up exactly when needed."},
    "LCK/GRIT": {"name": "Plot-Armor Holder", "tagline": "Surviving against the odds.", "blurb": "No matter what gets thrown at you, you make it through."},
    "tie_all": {"name": "The Balanced Blade", "tagline": "Jack of all trades, master of self.", "blurb": "You possess a rare equilibrium in all aspects of life."},
    "tie_VIT": {"name": "The Daylight Runner", "tagline": "Boundless physical energy.", "blurb": "You are at your best when you are moving."},
    "tie_INT": {"name": "The Archive Ghost", "tagline": "Lost in the library.", "blurb": "You are the ultimate seeker of hidden knowledge."},
    "tie_CHA": {"name": "The Room-Reader", "tagline": "Understanding without words.", "blurb": "You instantly grasp the emotional currents around you."}
}
